// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Context;

namespace Persistence.Migrations
{
    [DbContext(typeof(Db))]
    partial class DbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.EF.Cliente", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("codigo");

                    b.Property<string>("Endereco")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("endereco");

                    b.Property<string>("Nome")
                        .HasMaxLength(90)
                        .HasColumnType("nvarchar(90)")
                        .HasColumnName("nome");

                    b.Property<string>("Telefone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("telefone");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("Timestamp");

                    b.HasKey("Codigo");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("Domain.EF.Pedido", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("codigo")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodigoCliente")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("CodigoCliente");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("Timestamp");

                    b.Property<double>("Total")
                        .HasColumnType("float")
                        .HasColumnName("Total");

                    b.HasKey("Codigo");

                    b.HasIndex("CodigoCliente");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("Domain.EF.Pizza", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("codigo")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nome");

                    b.Property<int?>("PedidoCodigo")
                        .HasColumnType("int");

                    b.Property<double>("Valor")
                        .HasColumnType("float")
                        .HasColumnName("valor");

                    b.HasKey("Codigo");

                    b.HasIndex("PedidoCodigo");

                    b.ToTable("Pizza");
                });

            modelBuilder.Entity("Domain.EF.PizzaSabor", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("codigo")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CodigoPizza")
                        .HasColumnType("int");

                    b.Property<int>("CodigoSabor")
                        .HasColumnType("int");

                    b.HasKey("Codigo");

                    b.HasIndex("CodigoPizza");

                    b.HasIndex("CodigoSabor");

                    b.ToTable("PizzaSabor");
                });

            modelBuilder.Entity("Domain.EF.Sabor", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("codigo")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Disponivel")
                        .HasColumnType("bit")
                        .HasColumnName("disponivel");

                    b.Property<string>("Nome")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nome");

                    b.Property<double>("Valor")
                        .HasColumnType("float")
                        .HasColumnName("valor");

                    b.HasKey("Codigo");

                    b.ToTable("Sabor");
                });

            modelBuilder.Entity("Domain.EF.Pedido", b =>
                {
                    b.HasOne("Domain.EF.Cliente", "CodigoClienteNavigation")
                        .WithMany()
                        .HasForeignKey("CodigoCliente");

                    b.Navigation("CodigoClienteNavigation");
                });

            modelBuilder.Entity("Domain.EF.Pizza", b =>
                {
                    b.HasOne("Domain.EF.Pedido", null)
                        .WithMany("Pizzas")
                        .HasForeignKey("PedidoCodigo");
                });

            modelBuilder.Entity("Domain.EF.PizzaSabor", b =>
                {
                    b.HasOne("Domain.EF.Pizza", "PizzaNavigation")
                        .WithMany("Sabores")
                        .HasForeignKey("CodigoPizza")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.EF.Sabor", "SaborNavigation")
                        .WithMany()
                        .HasForeignKey("CodigoSabor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PizzaNavigation");

                    b.Navigation("SaborNavigation");
                });

            modelBuilder.Entity("Domain.EF.Pedido", b =>
                {
                    b.Navigation("Pizzas");
                });

            modelBuilder.Entity("Domain.EF.Pizza", b =>
                {
                    b.Navigation("Sabores");
                });
#pragma warning restore 612, 618
        }
    }
}
